# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b80edf990b9e67dd90ca2b510c1ca5482fa1ef93c60a177b1b36414207e362d2c70d44de8c939d836ab574ea37f880af386b049b2abcd4071d56ab509f6323f

test:
  secret_key_base: f3e8e2bfd50b5e3c32ea1a0152a88ac8593996d8e810ca56edd99940010ce0072fd73d98434b4e4669d7e516afb56adda09b3f13c59ed0364fe1ae6616d7f10a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
